using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace RequiemNexus.Data.Migrations
{
    /// <inheritdoc />
    public partial class FixPostgresIdentityColumns : Migration
    {
        /// <inheritdoc />
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            // All migrations were generated against SQLite, which uses "Sqlite:Autoincrement" annotations
            // that Npgsql ignores. As a result every int PK column was created as plain INTEGER NOT NULL
            // without a PostgreSQL identity sequence. EF Core still emits INSERT without Id (expecting
            // the database to auto-generate), which fails with a NOT NULL violation.
            //
            // This migration finds every integer primary key column in the public schema that has no
            // identity generation and no column default, then adds GENERATED BY DEFAULT AS IDENTITY.
            migrationBuilder.Sql(@"
DO $$
DECLARE
    col_rec RECORD;
BEGIN
    FOR col_rec IN
        SELECT c.table_name, c.column_name
        FROM information_schema.columns c
        JOIN information_schema.table_constraints tc
            ON tc.table_name = c.table_name
            AND tc.table_schema = c.table_schema
            AND tc.constraint_type = 'PRIMARY KEY'
        JOIN information_schema.key_column_usage kcu
            ON kcu.constraint_name = tc.constraint_name
            AND kcu.table_name = c.table_name
            AND kcu.table_schema = c.table_schema
            AND kcu.column_name = c.column_name
        WHERE c.table_schema = 'public'
          AND c.data_type = 'integer'
          AND c.identity_generation IS NULL
          AND c.column_default IS NULL
    LOOP
        EXECUTE format(
            'ALTER TABLE public.%I ALTER COLUMN %I ADD GENERATED BY DEFAULT AS IDENTITY',
            col_rec.table_name,
            col_rec.column_name
        );
    END LOOP;
END $$;
");
        }

        /// <inheritdoc />
        protected override void Down(MigrationBuilder migrationBuilder)
        {
            // Identity cannot be safely removed without knowing the original state.
            // This is intentionally a no-op — identity on int PKs is the correct permanent state.
        }
    }
}
