#pragma warning disable S1192 // String literals should not be duplicated
// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using RequiemNexus.Data;

#nullable disable

namespace RequiemNexus.Data.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260221072333_InitialDataSchema")]
    partial class InitialDataSchema
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.3");

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        ;

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        ;

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        ;

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        ;

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        ;

                    b.Property<string>("ClaimType")
                        ;

                    b.Property<string>("ClaimValue")
                        ;

                    b.Property<string>("RoleId")
                        .IsRequired()
                        ;

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        ;

                    b.Property<string>("ClaimType")
                        ;

                    b.Property<string>("ClaimValue")
                        ;

                    b.Property<string>("UserId")
                        .IsRequired()
                        ;

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        ;

                    b.Property<string>("ProviderKey")
                        ;

                    b.Property<string>("ProviderDisplayName")
                        ;

                    b.Property<string>("UserId")
                        .IsRequired()
                        ;

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        ;

                    b.Property<string>("RoleId")
                        ;

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        ;

                    b.Property<string>("LoginProvider")
                        ;

                    b.Property<string>("Name")
                        ;

                    b.Property<string>("Value")
                        ;

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("RequiemNexus.Data.Models.ApplicationUser", b =>
                {
                    b.Property<string>("Id")
                        ;

                    b.Property<int>("AccessFailedCount")
                        ;

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        ;

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        ;

                    b.Property<bool>("EmailConfirmed")
                        ;

                    b.Property<bool>("LockoutEnabled")
                        ;

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        ;

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        ;

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        ;

                    b.Property<string>("PasswordHash")
                        ;

                    b.Property<string>("PhoneNumber")
                        ;

                    b.Property<bool>("PhoneNumberConfirmed")
                        ;

                    b.Property<string>("SecurityStamp")
                        ;

                    b.Property<bool>("TwoFactorEnabled")
                        ;

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        ;

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("RequiemNexus.Data.Models.Character", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        ;

                    b.Property<string>("ApplicationUserId")
                        .IsRequired()
                        ;

                    b.Property<int>("BloodPotency")
                        ;

                    b.Property<int?>("ClanId")
                        ;

                    b.Property<int>("Health")
                        ;

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        ;

                    b.Property<int>("Vitae")
                        ;

                    b.Property<int>("Willpower")
                        ;

                    b.HasKey("Id");

                    b.HasIndex("ApplicationUserId");

                    b.HasIndex("ClanId");

                    b.ToTable("Characters");
                });

            modelBuilder.Entity("RequiemNexus.Data.Models.Clan", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        ;

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(250)
                        ;

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        ;

                    b.HasKey("Id");

                    b.ToTable("Clans");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("RequiemNexus.Data.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("RequiemNexus.Data.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("RequiemNexus.Data.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("RequiemNexus.Data.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("RequiemNexus.Data.Models.Character", b =>
                {
                    b.HasOne("RequiemNexus.Data.Models.ApplicationUser", "User")
                        .WithMany("Characters")
                        .HasForeignKey("ApplicationUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("RequiemNexus.Data.Models.Clan", "Clan")
                        .WithMany("Characters")
                        .HasForeignKey("ClanId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Clan");

                    b.Navigation("User");
                });

            modelBuilder.Entity("RequiemNexus.Data.Models.ApplicationUser", b =>
                {
                    b.Navigation("Characters");
                });

            modelBuilder.Entity("RequiemNexus.Data.Models.Clan", b =>
                {
                    b.Navigation("Characters");
                });
#pragma warning restore 612, 618
        }
    }
}

