using RequiemNexus.Domain.Contracts;
using RequiemNexus.Domain.Models;

namespace RequiemNexus.Domain.Services;

public class DiceService : IDiceService
{
    public RollResult Roll(int dicePool, bool tenAgain = true, bool nineAgain = false, bool eightAgain = false, bool isRote = false, int? seed = null)
    {
#pragma warning disable S2245 // Using pseudorandom number generators (PRNGs) is security-sensitive
        var random = seed.HasValue ? new Random(seed.Value) : Random.Shared;
#pragma warning restore S2245 // Using pseudorandom number generators (PRNGs) is security-sensitive

        if (dicePool <= 0)
        {
            return RollChanceDie(random);
        }

        return RollRegularPool(random, dicePool, tenAgain, nineAgain, eightAgain, isRote);
    }

    private static RollResult RollChanceDie(Random random)
    {
        var result = new RollResult();
        int roll = random.Next(1, 11);
        result.DiceRolled.Add(roll);

        if (roll == 10)
            result.Successes = 1;
        else if (roll == 1)
            result.IsDramaticFailure = true;

        return result;
    }

    private static RollResult RollRegularPool(Random random, int dicePool, bool tenAgain, bool nineAgain, bool eightAgain, bool isRote)
    {
        var result = new RollResult();
        int successes = 0;
        int diceToRoll = dicePool;

        while (diceToRoll > 0)
        {
            var batchResult = ProcessDiceRollBatch(random, diceToRoll, tenAgain, nineAgain, eightAgain, isRote, result);
            diceToRoll = batchResult.AdditionalDice;
            successes += batchResult.NewSuccesses;

            // Rote only applies to the initial pool, not exploding dice
            isRote = false;
        }

        result.Successes = successes;
        return result;
    }

    private static (int AdditionalDice, int NewSuccesses) ProcessDiceRollBatch(Random random, int diceToRoll, bool tenAgain, bool nineAgain, bool eightAgain, bool isRote, RollResult result)
    {
        int additionalDice = 0;
        int newSuccesses = 0;

        for (int i = 0; i < diceToRoll; i++)
        {
            int roll = random.Next(1, 11);
            result.DiceRolled.Add(roll);

            if (roll >= 8)
            {
                newSuccesses++;
                additionalDice += CalculateExplosions(roll, tenAgain, nineAgain, eightAgain);
            }
            else if (isRote)
            {
                // Rote action: reroll failed dice once. 
                // In VtR 2e, if the reroll is a success, it can also explode if it meets the again-rule criteria.
                int reroll = random.Next(1, 11);
                result.DiceRolled.Add(reroll);
                if (reroll >= 8)
                {
                    newSuccesses++;
                    additionalDice += CalculateExplosions(reroll, tenAgain, nineAgain, eightAgain);
                }
            }
        }

        return (additionalDice, newSuccesses);
    }

    /// <summary>
    /// Calculates the number of additional dice generated by a roll based on active again-rules.
    /// Rules are evaluated independently to prevent mutual exclusivity bugs (e.g., 10-again and 8-again both active).
    /// </summary>
    private static int CalculateExplosions(int roll, bool tenAgain, bool nineAgain, bool eightAgain)
    {
        int explosions = 0;
        if (tenAgain && roll >= 10) explosions++;
        if (nineAgain && roll == 9) explosions++;
        if (eightAgain && roll == 8) explosions++;
        return explosions;
    }
}
