name: PR Checks

on:
  pull_request:
    branches: [ main ]

permissions:
  contents: read

jobs:
  checks:
    uses: ./.github/workflows/_checks-reusable.yml
    with:
      artifact-retention-days: 7
